[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ## {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | trim | replace(from="@Action", to="`@Action`") | replace(from="@Waiting For", to="`@Waiting For`") | replace(from="@Reference", to="`@Reference`") }}
        {% if commit.body %}
            {% for line in commit.body | split(pat="\n") %}
          {{ line | replace(from="@Action", to="`@Action`") | replace(from="@Waiting For", to="`@Waiting For`") | replace(from="@Reference", to="`@Reference`") }}
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^style", group = "Style" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Miscellaneous" },
    { message = "^build", group = "Build System" },
]
